version: "3.9"
services:
  gateway:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/gateway-dv
    ports:
      - target: 80
        published: 81
        protocol: tcp
        mode: host
      - target: 443
        published: 444
        protocol: tcp
        mode: host
    volumes:
      - "frontend:/srv/www"
      - "/var/www:/var/www"
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "app-api"
      - "auth-api"
      - "app-ui"
  wss-njs:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/wss-njs-dv
    ports:
      - target: 3000
        published: 8444
        protocol: tcp
        mode: host
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-ui:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/app-ui-dv
    volumes:
      - "frontend:/srv/www"
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
  auth-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/auth-api-dv
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/app-api-dv
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-manto-unidades-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/app-manto-unidades-api-dv
    volumes:
      - "./app-manto-unidades-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/app-manto-unidades-api:/srv/siamt/code/app-manto-unidades-api"
      - "../code/common-php:/srv/siamt/code/common-php"
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  signature-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/signature-api-dv
    volumes:
      - "./signature-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/signature-api:/srv/siamt/code/signature-api"
      - "../code/common-php:/srv/siamt/code/common-php"
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-inspections-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/app-inspections-api-dv
    volumes:
      - "./app-inspections-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/app-inspections-api:/srv/siamt/code/app-inspections-api"
      - "../code/common-php:/srv/siamt/code/common-php"
      - "app-inspections-files:/srv/app-inspections-files"
      - "./app-inspections-api/init.sh:/docker-entrypoint.d/local/init.sh"
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-procedures-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/app-procedures-api-dv
    volumes:
      - "./app-procedures-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/app-procedures-api:/srv/siamt/code/app-procedures-api"
      - "../code/common-php:/srv/siamt/code/common-php"
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  redis:
    image: redis
    volumes:
      - "queue:/data"
    networks:
      - internal-services
    sysctls:
      net.core.somaxconn: 1024
  liquibase:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/liquibase-dv
    env_file:
      - ../../../.dv-env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  frontend:
  queue:
  app-inspections-files:
networks:
  internal-services:
    ipam:
      driver: default
      config:
        - subnet: "172.31.120.0/21"