FROM debian:bullseye-slim as BUILDER

ENV PHALCON_VERSION 4.1.3
ENV ZEPHIR_VERSION 0.13.5
ENV ZEPHIR_PARSER_VERSION 1.3.8
ENV PSR_VERSION 1.1.0

RUN set -x && \
    apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y wget \
        ca-certificates php-dev php-xml re2c libpcre3-dev make php-pear && \
    pecl install psr-${PSR_VERSION} && \
    echo "extension=psr.so" > /etc/php/7.4/cli/conf.d/20-psr.ini && \

    wget https://github.com/zephir-lang/php-zephir-parser/archive/refs/tags/v${ZEPHIR_PARSER_VERSION}.tar.gz && \
    wget https://github.com/zephir-lang/zephir/releases/download/${ZEPHIR_VERSION}/zephir.phar && \
    wget https://github.com/phalcon/cphalcon/archive/refs/tags/v${PHALCON_VERSION}.tar.gz && \
    for f in *.gz; do tar xf "$f"; done && chmod +x zephir.phar && ln -s /cphalcon-${PHALCON_VERSION} /cphalcon && \
    cd /php-zephir-parser-${ZEPHIR_PARSER_VERSION} && phpize && ./configure && make && make install && \
    echo "extension=zephir_parser.so" > /etc/php/7.4/cli/conf.d/30-zephir-parser.ini && \
    cd /cphalcon-${PHALCON_VERSION} && /zephir.phar fullclean && /zephir.phar build

FROM debian:bullseye-slim

RUN set -x && \
    apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y curl gnupg2 git ca-certificates && \
    curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | \
        tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null && \
    apt-get remove --purge --auto-remove -y gnupg2 && rm -rf /var/lib/apt/lists/*  && \
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
        https://packages.nginx.org/unit/debian/ bullseye unit" >> /etc/apt/sources.list.d/unit.list && \
    apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y \
        unit-php \
        php-mbstring \
        php-zip \
        php-gd \
        php-xml \
        php-pgsql \
        php-redis  \
        php-curl  \
        && \
    apt-get clean && \
    #apt-get remove --purge --auto-remove -y ca-certificates && \
    rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/unit.list && \
    echo "extension=psr.so" > /etc/php/7.4/embed/conf.d/20-psr.ini && \
    echo "extension=phalcon.so" > /etc/php/7.4/embed/conf.d/30-phalcon.ini && \
    mkdir /docker-entrypoint.d && \
    ln -sf /dev/stdout /var/log/unit.log

COPY docker-entrypoint.sh /
CMD chmod +x /docker-entrypoint.sh

COPY init.sh /docker-entrypoint.d/
COPY --from=BUILDER /usr/lib/php/20190902/psr.so /usr/lib/php/20190902/psr.so
COPY --from=BUILDER /cphalcon/ext/modules/phalcon.so /usr/lib/php/20190902/phalcon.so


EXPOSE 8000

STOPSIGNAL SIGTERM

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["unitd", "--no-daemon", "--control", "unix:/var/run/control.unit.sock"]