const BASE_URL = "https://" + location.host + "/api"

export default {
  authUrl: BASE_URL + "/auth",
  appUrl: BASE_URL + "/app",
  usersUrl: BASE_URL + "/users",
  profilesUrl: BASE_URL + "/profiles",
  eventUrl: BASE_URL + "/events",
  adminUrl: BASE_URL + "/admin",
  mantounidadesUrl: BASE_URL + "/mantounidades",
  inspectionsUrl: BASE_URL + "/inspections",
  personsUrl: BASE_URL + "/persons",
  structureUrl: BASE_URL + "/structure",
  dwhUrl: BASE_URL + "/dwh",
  censusUrl : BASE_URL + "/census",
  statsUrl: BASE_URL + "/stats",
  assignmentsUrl: BASE_URL + "/assignments",
  dashboardUrl : BASE_URL + "/dashboard",
  campaignsUrl : BASE_URL + "/dialogue/campaigns",
  dialogueUrl : BASE_URL + "/dialogue",
  callcenterUrl : BASE_URL + "/callcenter",
  trackerUrl : BASE_URL + "/tracker",
  comitesUrl : BASE_URL + "/comites",
  finderUrl : BASE_URL + "/finder",
  signatureUrl : BASE_URL + "/signature",
}
