version: "3.9"
services:
  gateway:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/gateway
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "./gateway/conf:/etc/nginx"
      - "app-inspections-files:/srv/app-inspections-files"
    env_file:
      - dv.env
    networks:
      - internal-services
    depends_on:
      - "app-api"
      - "auth-api"
      - "app-ui"
  wss-njs:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-njs-16
    command: ["node", "/srv/siamt/code/wss-njs/app.js"]
    ports:
      - target: 3000
        published: 8443
        protocol: tcp
        mode: host
    volumes:
      - "../code/wss-njs:/srv/siamt/code/wss-njs"
      - "../code/common-njs:/srv/siamt/code/common-njs"
    env_file:
      - dv.env
    networks:
      - internal-services
    depends_on:
      - "liquibase"
      - "redis"
  app-ui:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-njs-16
    command: ["yarn","--cwd","/srv/siamt/code/app-ui","serve"]
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "81:3000"
    volumes:
      - "../code/app-ui:/srv/siamt/code/app-ui"
    env_file:
      - dv.env
    networks:
      - internal-services
  auth-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-api
    volumes:
      - "./auth-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/auth-api:/srv/siamt/code/auth-api"
      - "../code/common-php:/srv/siamt/code/common-php"
    env_file:
      - dv.env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-api
    volumes:
      - "./app-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/app-api:/srv/siamt/code/app-api"
      - "../code/common-php:/srv/siamt/code/common-php"
      - "/srv/app-manto-files:/srv/app-manto-files"
    env_file:
      - dv.env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
  app-manto-unidades-api:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-api
    volumes:
      - "./app-manto-unidades-api/config.json:/docker-entrypoint.d/config.json"
      - "../code/app-manto-unidades-api:/srv/siamt/code/app-manto-unidades-api"
      - "../code/common-php:/srv/siamt/code/common-php"
      - "/srv/app-manto-files:/srv/app-manto-files"
      - "./app-manto-api/init.sh:/docker-entrypoint.d/local/init.sh"
    env_file:
      - dv.env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "liquibase"
      - "redis"
#  users-api:
#    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-api
#    volumes:
#      - "./users-api/config.json:/docker-entrypoint.d/config.json"
#      - "../code/users-api:/srv/siamt/code/users-api"
#      - "../code/common-php:/srv/siamt/code/common-php"
#    env_file:
#      - dv.env
#    networks:
#      - internal-services
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    depends_on:
#      - "liquibase"
#      - "redis"
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - internal-services
    sysctls:
      net.core.somaxconn: 1024
  liquibase:
    image: gitaty.transporteyucatan.org.mx:5050/aty/siamt/liquibase
    volumes:
      - "../containers/liquibase/init.sh:/docker-entrypoint.d/init.sh"
      - "../code/migrations:/liquibase/changelog"
      - "../code/migrations_inspectores:/liquibase/changelog/inspeccion"
      - "../code/migrations_manto:/liquibase/changelog/manto"
      - "../code/migrations_firma:/liquibase/changelog/firma"
      - "../code/migrations_operadores:/liquibase/changelog/operadores"
      - "../code/migrations_procedure:/liquibase/changelog/procedure"
    env_file:
      - dv.env
    networks:
      - internal-services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_OPTS: "-Xmx4096m"
volumes:
  app-inspections-files:
networks:
  internal-services:
    ipam:
      driver: default
      config:
        - subnet: "172.23.16.0/21"