FROM debian:bullseye-slim

ENV NGINX_VERSION   1.20.1
ENV NJS_VERSION     0.6.2
ENV PKG_RELEASE     1~bullseye

RUN set -ex && \
    apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y curl gnupg2 ca-certificates && \
    curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | \
        tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null && \

    apt-get remove --purge --auto-remove -y gnupg2 && rm -rf /var/lib/apt/lists/*  && \
    nginxPackages=" \
        nginx=${NGINX_VERSION}-${PKG_RELEASE} \
        #nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
        #nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
        #nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
        #nginx-module-njs=${NGINX_VERSION}+${NJS_VERSION}-${PKG_RELEASE} \
    " && \
    echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
        https://nginx.org/packages/debian/ bullseye nginx" >> /etc/apt/sources.list.d/nginx.list && \

    apt-get update && \
    apt-get install --no-install-recommends --no-install-suggests -y \
        $nginxPackages \
        gettext-base && \

    curl -L https://github.com/icy/genvsub/releases/download/v1.2.3/genvsub_1.2.3_Linux_x86_64.tar.gz | tar -xzC /usr/bin && \
    apt-get remove --purge --auto-remove -y && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

COPY docker-entrypoint.sh /

EXPOSE 80 443

STOPSIGNAL SIGTERM

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]