FROM gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-api

ARG GIT_USR=$GIT_USR
ARG GIT_PASS=$GIT_PASS

COPY config.json /docker-entrypoint.d

RUN set -ex && \
    git clone --branch unstable --depth 1 --filter=blob:none --sparse https://$GIT_USR:$GIT_PASS@gitaty.transporteyucatan.org.mx/aty/siamt.git /srv/siamt && \
    cd /srv/siamt && \
    git sparse-checkout add code/common-php code/signature-api
