FROM gitaty.transporteyucatan.org.mx:5050/aty/siamt/base-njs-16

ARG GIT_USR=$GIT_USR
ARG GIT_PASS=$GIT_PASS

RUN set -ex && \
    git clone --depth 1 --filter=blob:none --sparse https://$GIT_USR:$GIT_PASS@gitaty.transporteyucatan.org.mx/aty/siamt.git /srv/siamt && \
    cd /srv/siamt && \
    git sparse-checkout add code/common-njs code/wss-njs && \
    cd /srv/siamt/code/common-njs && npm install && \
    cd /srv/siamt/code/wss-njs && npm install && \
    rm /docker-entrypoint.d/init.sh

CMD ["node", "/srv/siamt/code/wss-njs/app.js"]